// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiZCWG6hbEcy7i1B1QvslcFhPIzm7pwo',
    appId: '1:734487048019:web:e142145863652369c1bba6',
    messagingSenderId: '734487048019',
    projectId: 'eco-routing',
    authDomain: 'eco-routing.firebaseapp.com',
    storageBucket: 'eco-routing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-WjdtrMLuhsKu9uVnW7mfeVpAFmPh6W8',
    appId: '1:734487048019:android:1aac6b1b9c98bbffc1bba6',
    messagingSenderId: '734487048019',
    projectId: 'eco-routing',
    storageBucket: 'eco-routing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVSyG7jH4PYoD6idLmrD2ZnzDc_8r4sso',
    appId: '1:734487048019:ios:773563de7e8522f5c1bba6',
    messagingSenderId: '734487048019',
    projectId: 'eco-routing',
    storageBucket: 'eco-routing.appspot.com',
    iosBundleId: 'com.example.ecoRouting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVSyG7jH4PYoD6idLmrD2ZnzDc_8r4sso',
    appId: '1:734487048019:ios:773563de7e8522f5c1bba6',
    messagingSenderId: '734487048019',
    projectId: 'eco-routing',
    storageBucket: 'eco-routing.appspot.com',
    iosBundleId: 'com.example.ecoRouting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRiZCWG6hbEcy7i1B1QvslcFhPIzm7pwo',
    appId: '1:734487048019:web:1c6f0a6ee2588070c1bba6',
    messagingSenderId: '734487048019',
    projectId: 'eco-routing',
    authDomain: 'eco-routing.firebaseapp.com',
    storageBucket: 'eco-routing.appspot.com',
  );
}
